### ISSUE TITLE
Wrong DuckDNS TXT record update URL

### ISSUE THREAD

**Issue by lfhohmann** [alex3305/hassio-addons#7]
I'm trying to get Traefik+DuckDNS+LetsEncrypt to work on my hass.io system, this is my configuration:

```yaml
log_level: INFO
access_logs: false
forwarded_headers_insecure: false
dynamic_configuration_path: /share
letsencrypt:
  enabled: true
  email: EMAIL@EMAIL.COM
  challenge_type: dnsChallenge
  provider: duckdns
env_vars:
  - DUCKDNS_TOKEN=abcd1234efgh5678ijkl90
```

But it's unable to get the Certificates, it returns the following error:

```
time="2020-07-01T22:40:59-03:00" level=error msg="Unable to obtain ACME certificate for domains \"subdomain.domain.duckdns.org\": unable to generate a certificate for the domains [subdomain.domain.duckdns.org]: error: one or more domains had a problem:\n[subdomain.domain.duckdns.org] [subdomain.domain.duckdns.org] acme: error presenting token: request to change TXT record for DuckDNS returned the following result (KO) this does not match expectation (OK) used url [https://www.duckdns.org/update?clear=false&domains=domain.duckdns.org&token=abcd1234efgh5678ijkl90+&txt=ABCDEFGHTASDF]\n" providerName=le.acme rule="Host(`subdomain.domain.duckdns.org`)" routerName=homeAssistantRouter@file
```

Right after the token value and before de "&txt=" theres a plus sign, when I type that URL (with the plus sign) on Chrome navigator, it returns KO, but if I remove the plus sign (https://www.duckdns.org/update?clear=false&domains=domain.duckdns.org&token=abcd1234efgh5678ijkl90&txt=ABCDEFGHTASDF) it returns OK

Any idea on how can I solve this?

(EDIT: By the way, this is only preventing me from having a working certificate, routing works just fine, Traefik is able to redirect the "subdomain.domain.duckdns.org" to the proper internal url and port)
